apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ada-api
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: ada-staging-https-headers@kubernetescrd
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - ada-staging.scopeo.studio
      secretName: ada-tls
  rules:
    - host: ada-staging.scopeo.studio
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ada-api
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nango-server
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: ada-staging-https-headers@kubernetescrd
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - oauth-staging.draftnrun.com
      secretName: nango-tls
  rules:
    - host: oauth-staging.draftnrun.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nango-server
                port:
                  number: 3003
