apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - priority-classes.yaml
  - api-deployment.yaml
  - ingestion-worker-deployment.yaml
  - webhook-worker-deployment.yaml
  - scheduler-deployment.yaml
  - service.yaml
  - nango-db-statefulset.yaml
  - nango-deployment.yaml
  - nango-service.yaml
  - nango-network-policy.yaml
  - nango-ingress-middleware.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: ada
      app.kubernetes.io/managed-by: kustomize
